# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.34.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20023_dcc import InlineResponse20023Dcc  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20023Dcc(unittest.TestCase):
    """InlineResponse20023Dcc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023Dcc(self):
        """Test InlineResponse20023Dcc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20023_dcc.InlineResponse20023Dcc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
