# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.34.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20026_submerchant import InlineResponse20026Submerchant  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20026Submerchant(unittest.TestCase):
    """InlineResponse20026Submerchant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026Submerchant(self):
        """Test InlineResponse20026Submerchant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20026_submerchant.InlineResponse20026Submerchant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
