# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.34.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.order_execute_body import OrderExecuteBody  # noqa: E501
from swagger_client.rest import ApiException


class TestOrderExecuteBody(unittest.TestCase):
    """OrderExecuteBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderExecuteBody(self):
        """Test OrderExecuteBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.order_execute_body.OrderExecuteBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
